// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_array from "bs-platform/lib/es6/caml_array.js";

function swap(a, b, t) {
  var t_b = Caml_array.get(t, b);
  Caml_array.set(t, b, Caml_array.get(t, a));
  return Caml_array.set(t, a, t_b);
}

export {
  swap ,
  
}
/* No side effect */
