// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

function swap(a, b, t) {
  var t_b = Caml_array.get(t, b);
  Caml_array.set(t, b, Caml_array.get(t, a));
  return Caml_array.set(t, a, t_b);
}

exports.swap = swap;
/* No side effect */
